### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by osmanwako** [osmanwako/recipe_application#9]
### We are a group of **two(2)** members.
- [Osman Wako](https://github.com/osmanwako)
- [Emmanuel Nwoye ](https://github.com/Mikey1-nuel)
### This issue has a list of tasks prepared to do this week.
- We created an empty repository for our group project.
- Our project has **Todo, In Progress,In Review, and Done** columns.
- we have Created tasks on our Kanban board based on the project requirements
- Each task was separated  card that:
    - Has a descriptive title.
    - Has a description of the task.
- Each of the team members has assigned himself to the cards 
- Decide who will be the assignee for the cards marked as group tasks. 
- All cards on our Kanban board have assignees. 
- Our Project [here](https://github.com/users/osmanwako/projects/6)

**Comment by julie-ify** [comment]
## Hi @osmanwako and @Mikey1-nuel,

Good job so far!

## Highlights!
- Descriptive issue ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] Kindly add this task. It is missing.

  ![image](https://github.com/osmanwako/recipe_application/assets/81468675/fbff53fd-1a86-4ae5-9e5f-b280a7c0816a)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
